In [13]:
# Data Exploration

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
ds = pd.read_csv('../Data/e_commerce.csv')
ds

,account length,location code,user id,credit card info save,push status,add to wishlist,desktop sessions,app sessions,desktop transactions,total product detail views,session duration,promotion clicks,avg order value,sale product views,discount rate per visited products,product detail view per app session,app transactions,add to cart per session,customer service calls,churn
0,128,415,3824657,no,yes,25,265,45,17,110.0,197,87,244.7,91,11.01,10.0,3,2.70,1.0,0
1,107,415,3717191,no,yes,26,162,27,17,123.0,196,103,254.4,103,11.45,13.7,3,3.70,1.0,0
2,137,415,3581921,no,no,0,243,41,10,114.0,121,110,162.6,104,7.32,12.2,5,3.29,0.0,0
3,84,408,3759999,yes,no,0,299,51,5,71.0,62,88,196.9,89,8.86,6.6,7,1.78,2.0,0
4,75,415,3306626,yes,no,0,167,28,13,113.0,148,122,186.9,121,8.41,10.1,3,2.73,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,192,415,4144276,no,yes,36,156,27,18,77.0,216,126,279.1,83,12.56,9.9,6,2.67,2.0,0
3329,68,415,3703271,no,no,0,231,39,13,NaN,153,55,191.3,123,8.61,9.6,4,2.59,3.0,0
3330,28,510,3288230,no,no,0,181,31,25,109.0,289,58,191.9,91,8.64,14.1,6,3.81,2.0,0
3331,184,510,3646381,yes,no,0,214,36,14,105.0,160,84,139.2,137,6.26,5.0,10,1.35,2.0,0
3332,74,415,4004344,no,yes,25,234,40,23,113.0,266,82,241.4,77,10.86,13.7,4,3.70,0.0,0

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   account length                       3333 non-null   int64
 1   location code                        3333 non-null   int64
 2   user id                              3333 non-null   int64
 3   credit card info save                3333 non-null   object
 4   push status                          3333 non-null   object
 5   add to wishlist                      3333 non-null   int64
 6   desktop sessions                     3333 non-null   int64
 7   app sessions                         3333 non-null   int64
 8   desktop transactions                 3333 non-null   int64
 9   total product detail views           3281 non-null   float64
 10  session duration                     3333 non-null   int64
 11  promotion clicks                     3333 non-null   int64
 12  avg order value                      3333 non-null   float64
 13  sale product views                   3333 non-null   int64
 14  discount rate per visited products   3333 non-null   float64
 15  product detail view per app session  3272 non-null   float64
 16  app transactions                     3333 non-null   int64
 17  add to cart per session              3333 non-null   float64
 18  customer service calls               3274 non-null   float64
 19  churn                                3333 non-null   int64
dtypes: float64(6), int64(12), object(2)
memory usage: 520.9+ KB

In [4]:
ds.isna().sum()

account length                          0
location code                           0
user id                                 0
credit card info save                   0
push status                             0
add to wishlist                         0
desktop sessions                        0
app sessions                            0
desktop transactions                    0
total product detail views             52
session duration                        0
promotion clicks                        0
avg order value                         0
sale product views                      0
discount rate per visited products      0
product detail view per app session    61
app transactions                        0
add to cart per session                 0
customer service calls                 59
churn                                   0
dtype: int64

In [5]:
ds.nunique()

account length                          212
location code                             3
user id                                3333
credit card info save                     2
push status                               2
add to wishlist                          46
desktop sessions                        295
app sessions                             60
desktop transactions                     30
total product detail views              119
session duration                        287
promotion clicks                        123
avg order value                        1591
sale product views                      120
discount rate per visited products      933
product detail view per app session     162
app transactions                         21
add to cart per session                 162
customer service calls                   10
churn                                     2
dtype: int64